### ISSUE TITLE
[CHORE]: Modularise Bot

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TearDrops#10]
*This issue is currently not available. Will be executed sometime later.

**Comment by mikeysan** [comment]
I was about to open an issue to suggest this :) I'm guessing you're thinking of Cogs?

**Comment by Vyvy-vi** [comment]
yeah cogs...
This should be high priority

**Comment by Vyvy-vi** [comment]
@all-contributors add @mikeysan for ideas

**Comment by Vyvy-vi** [comment]
closed by #117
