### ISSUE TITLE
[CHORE]: Make dictionary for quotes, rather than using lists

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TearDrops#100]
# Chore Request:

The bot currently fetches inputs from the input.py file for the `qq quote` command.
Now, since we have embedded the command, we don't want it to look like this-
![Screenshot 2020-11-06 at 5 50 17 PM](https://user-images.githubusercontent.com/62864373/98365543-95f4ee80-2058-11eb-94f9-f92d44bd279b.png)
This doesn't look good.

## Work to be done:

Make a dictionary in the inputs.py file for the quote list, indexed as `{'<quote>':' <author>'}`
This would make fetching the author's name easy, which we can then embed as a footer for the quote command.

**Comment by LazybuddyNK** [comment]
I would like to do this.

**Comment by Vyvy-vi** [comment]
resolved by #101
