### ISSUE TITLE
[BUG]: Wiki Command Issues

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TearDrops#111]
# Bug Report-->

## Describe the bug:
The bot wiki command often doesn't show results related to searched args.
Might need investigating.

## Expected behavior
print the wiki article for the search argument or give a list of recommendation

## Screenshots
![Screenshot 2020-11-08 at 4 11 40 AM](https://user-images.githubusercontent.com/62864373/98452795-88368a80-2178-11eb-927a-57422b7e4c8c.png)

## Additional information
This might be much more of a module issue/config issue.

**Comment by IcemanEtika** [comment]
Hey, I'll work on this
