### ISSUE TITLE
[IDEA]: API for getting book recommendations

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TearDrops#120]
# Suggestion(IDEAS)

## Describe the IDEA

It would be great if we can fetch the Goodreads from a site using `requests` / `urllib` / `aiohttp`
This would ensure:
1- larger

## A small survey- (optional)

1- Would you like to work on this idea?
- [] Yes
- [] No
- [x] Either
2- Is this idea an original idea or something you have seen elsewhere?
- [x] It is original.
- [] No, I saw this somewhere.
- [] Prefer not to say.

3- If you have seen this idea somewhere, can you state where?

huh. not sure where I got the idea from
Oh wait that's right: brickwalling lists in a file is inefficient.

4- How much would you rate the current version of the bot?

- [] Amazing(5/5)
- [] Good(4/5)
- [] Not Bad(3/5)
- [] Meh(2/5)
- [] It succ(1/5)

- [x] Sad, depressing and makes me want to cry

## Additional information

._.

**Comment by lakshya12345** [comment]
@Vyvy-vi we can use google books api

**Comment by Vyvy-vi** [comment]
We could use that, however, correct me if I am wrong, but Google Books API doesn't have a recommendation system(we'll have to make our own bookshelf), right?

What about something trimmed down like `goodreads`?

**Comment by lakshya12345** [comment]
@Vyvy-vi i want to ask you that i have started coding in python and html,css. i am currently in my 6th class. can you give me guidence how can i contribute in big projects

**Comment by Vyvy-vi** [comment]
That's great-!
tbh, you don't need to contribute to big repos, to contribute to opensource. Mid-level or small projects that align with your thoughts, and you like would also be great to contribute to.

For starting out, you could make issues on big projects regarding perhaps issues with documentation or broken links/images in their files or in their README. You could also report about dependencies and outdated dependencies(these could be missed out by the maintainers and this might break things on the project). You can make issues if something isn't working as expected or if there is a better way to do something in the project and even raise PRs for fixes to this or for improving their pre-existing docs. Example: Say you are using a new python library and you read the documentation and something doesn't check out or you can't understand something or if you can't understand how to contribute to that project. Go raise an issue on their repo for this, and if you find the answer/solution and it was missing from docs, open a PR for it. 

I would suggest that you play and learn more with regard to HTML, css and python, python libraries and start contributing to small/medium sized projects. IMHO, you don't need to open a PR to `Flask` or `React` or big projects while just starting out but much rather focus on contributing to projects that you _like_ or _use_ .

> "Open source is like brushing your teeth. You can't brush a lot on the first day and then not brush for the entire week. Similarly, in opensource, you can't contribute to one big project once and make 500 commits in one day and be done with it. It's much more like doing small chunks every day and it's totally fine _if_ you miss a day or two. (Those small contributions to small/medium projects definitely count and are helping the community **and** boosting your CV and giving you opportunities to learn more)"

~ Eddie Jaoude 

Best of Luck :) 🟩  (hope to see you around)

Are you on discord?
(we can discuss more over there)
OR open a discussion here: https://github.com/EddieJaoudeCommunity/support/discussions/new [you can get advice from a lot of people over there]

**Comment by eddiejaoude** [comment]
Thanks for the shoutout @Vyvy-vi 🤓
