### ISSUE TITLE
[IDEA] Code Of Conduct

### ISSUE THREAD

**Issue by AllanRegush** [Vyvy-vi/TearDrops#127]
# Suggestion(IDEAS)

## Describe the IDEA

Add Code Of Conduct

## A small survey- (optional)

1- Would you like to work on this idea?
- [x] Yes
- [ ] No

2- Is this idea an original idea or something you have seen elsewhere?
- [ ] It is original.
- [x] No, I saw this somewhere.
- [ ] Prefer not to say.

3- If you have seen this idea somewhere, can you state where?

Various opensource projects.

4- How much would you rate the current version of the bot?

- [ ] Amazing(5/5)
- [ ] Good(4/5)
- [x] Not Bad(3/5) - Have not used the bot.
- [ ] Meh(2/5)
- [ ] It succ(1/5)

- [ ] Sad, depressing and makes me want to cry

**Comment by Vyvy-vi** [comment]
@all-contributors add @AllanRegush for docs, ideas
