### ISSUE TITLE
[FEAT]: Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TearDrops#13]
up-for-grabs
preferably something that emphasis no-SPAM and usage of [Commit Guidelines](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by anubhavcodes** [comment]
@Vyvy-vi Let me take this up. ;)

**Comment by Vyvy-vi** [comment]
Thanks!
