### ISSUE TITLE
[FEAT]: add Announce Command

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TearDrops#148]
# Feature Request

## Is your feature request related to a problem? Please describe:

The current `say` and `echo` command, act as potential threats to the chat environment.
Thus, these will be replaced by an `announce` command, which would increase the utility of the bot.
These would be added in a new cog titled `Moderation`. 
 
## Describe the solution you'd like

A new `announce` command

**Comment by Vyvy-vi** [comment]
@all-contributors add @nhcarrigan for ideas

**Comment by nhcarrigan** [comment]
@Vyvy-vi Stalebot really wants to close this.
