### ISSUE TITLE
Wrong status in user command

### ISSUE THREAD

**Issue by SKULLXL** [Vyvy-vi/TearDrops#151]
# Bug Report

## Describe the bug
The bug is in the new command `qq user` There the status shown is wrong. Tho i am in online mode it shows i am offline.

## Expected behavior
The status should have been shown as **online**

## Screenshots
![image](https://user-images.githubusercontent.com/68315325/100189859-5b73c880-2f17-11eb-887b-1f32a3baf86d.png)

**Comment by Vyvy-vi** [comment]
@all-contributors add @SKULLXL for bugs
