### ISSUE TITLE
[BUG] Broken Image in README.md

### ISSUE THREAD

**Issue by AkshayaKulasekaran** [Vyvy-vi/TearDrops#156]
# Bug Report

## Describe the bug

One of the images/gifs is broken. A screenshot of the same is attached below

## Screenshots

![image](https://user-images.githubusercontent.com/61582763/101262715-b2bf3780-3766-11eb-8de8-66bd74ab32f0.png)

## Additional information

I think it might be of an accidental newline in the README.md file

**Comment by AkshayaKulasekaran** [comment]
Actually, it looks like it might have been deleted/moved:

<img src="https://user-images.githubusercontent.com/61582763/101262827-5dcff100-3767-11eb-9138-f67dff006d37.png" height="250px">

**Comment by Vyvy-vi** [comment]
Thanks for the bug-report!

Which branch is that on?
that's strange 🤔 
It works for me on the `main` branch

![Screenshot 2020-12-06 at 1 36 16 PM](https://user-images.githubusercontent.com/62864373/101274969-365d4080-37c8-11eb-8a34-26d0f8b93cba.png)

**Comment by Vyvy-vi** [comment]
@all-contributors add @AkshayaKulasekaran for bugs

**Comment by AkshayaKulasekaran** [comment]
@Vyvy-vi, looks like it's on the main branch. Maybe the site can't be accessed from specific locations?

Is it a picture? If so, you might want to upload a picture to a file or an issue and link it to that... If it's a gif you need to upload it as a file

**Comment by Vyvy-vi** [comment]
Thank you for contributing to this project! 🎉

**Comment by Vyvy-vi** [comment]
Re-added the image via #164 
Does it load properly now?

**Comment by AkshayaKulasekaran** [comment]
Yup, it's visible now 👍
