### ISSUE TITLE
[FEAT]: Make Time Fetch Command 

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TearDrops#16]
Make a command to fetch the current time, it must allow user to select the timezone.
Like, qq time <UTC+3> or qq time <EST>

**Comment by Vyvy-vi** [comment]
Another beta+ idea is to add a field in the current db for setting your timezone.
This will allow user to just do qq time

**Comment by sayand0122** [comment]
> Make a command to fetch the current time, it must allow user to select the timezone.
> Like, qq time <UTC+3> or qq time

Can you please elaborate this command?

**Comment by Vyvy-vi** [comment]
basically this lets the user convert timezones
So, say I am in UTC and you are in UTC + 3
So, you need to just do-
qq time <current-time> <timezone> | <timezone to convert to>

**Comment by sayand0122** [comment]
ok...i will create a prototype of this👍🏻

**Comment by Vyvy-vi** [comment]
What's the plan?
argument parsing using special characters or something else?(I'm curious to which all approaches can be taken for this)

**Comment by sayand0122** [comment]
Really sorry but my mids will be starting from tomorrow but i have an idea... i am thinking to use cogs for it... coz this itself is a lengthy thing to convert one timezone to another and the command will be as simple as --prefix "this utc" "that utc"-- and time will be fetched as current time.

**Comment by Vyvy-vi** [comment]
No wories.
(this command isn't essential rn, so can wait a few weeks)

**Comment by Vyvy-vi** [comment]
@sayand0122 Would you like to keep working on this issue?
If you're busy, I could clear your assignment

**Comment by sayand0122** [comment]
Yeah i am actually busy. So please clear out the assignment.
