### ISSUE TITLE
[IDEA]: Add a feature to spend tears.

### ISSUE THREAD

**Issue by jveer634** [Vyvy-vi/TearDrops#165]
# Suggestion(IDEAS)

## Describe the IDEA

There is no opt available for spending the tears cried other than earning and transferring.
So, I propose an idea to implement some games which requires to use their tears either by betting or as an entry free.

## A small survey- (optional)

1- Would you like to work on this idea?
- [ ] Yes 
- [ ] No

2- Is this idea an original idea or something you have seen elsewhere?
- [x] It is original.
- [ ] No, I saw this somewhere.
- [ ] Prefer not to say.

3- If you have seen this idea somewhere, can you state where?

4- How much would you rate the current version of the bot?

- [ ] Amazing(5/5)
- [ ] Good(4/5)
- [x] Not Bad(3/5)
- [ ] Meh(2/5)
- [ ] It succ(1/5)

- [ ] Sad, depressing and makes me want to cry

**Comment by Vyvy-vi** [comment]
We would work on this after `v1.1` 👍 
Thank you for contributing to TearDrops!

**Comment by jveer634** [comment]
How about we add a trivia game?

**Comment by Vyvy-vi** [comment]
hmm that could be done
not sure how the game makes ppl spend 💰 
Would you like to work on that?

(Open a new issue for that, so that we can continue the conversation there)
