### ISSUE TITLE
[FEAT]-Have  custom-subreddit specification

### ISSUE THREAD

**Issue by SKULLXL** [Vyvy-vi/TearDrops#166]
# Feature Request

## Is your feature request related to a problem? Please describe:
Most memes that you can get from the `qq meme` command are from r/me_irl

## Describe the solution you'd like
If we have a command to specify a subreddit or a command that can fetch memes from completely different subreddits it will be better.

**Comment by Vyvy-vi** [comment]
this would be worked on 👍 
Do you want to work on this?
It's sort of a simple fix

**Comment by Vyvy-vi** [comment]
thanks for contributing to EddieBot

**Comment by Vyvy-vi** [comment]
@all-contributors add @SKULLXL for ideas

**Comment by Vyvy-vi** [comment]
closed by 48f49f7
