### ISSUE TITLE
[DOCS] add section about how to contribute

### ISSUE THREAD

**Issue by mstanciu552** [Vyvy-vi/TearDrops#168]
# Incorrect Documentation

## Describe the error

There is a [CONTRIBUTING.md](https://github.com/Vyvy-vi/TearDrops/blob/main/CONTRIBUTING.md), but it is very long and it describes guidelines and how to actually contribute.

## Expected information

I think we should add a concise description on how to contribute in README.md so that it could be seen when entering the repo and also a link to the [CONTRIBUTING.ms](https://github.com/Vyvy-vi/TearDrops/blob/main/CONTRIBUTING.md) for those who are just starting with open source.

## Additional information

Please share your thoughts on the matter.
Also mention if this issue has a point or if it is unnecesary. 👍

**Comment by Vyvy-vi** [comment]
This is very essential 👍 
(The plan was to add a proper "`how to host the bot locally and contribute`" section inside the README, but that never got made). Would you like to work on this issue?

hmm this was supposed to be addressed in #3

**Comment by mstanciu552** [comment]
I will work on this.
Thank you very much.
