### ISSUE TITLE
[FEAT] Trivia Game with bot

### ISSUE THREAD

**Issue by jveer634** [Vyvy-vi/TearDrops#175]
# Feature Request

To spend tears cried.

## Describe the solution you'd like

We can add a trivia game using any online api so that there will be a way to spend our tears.

## Additional context

We could maintain a leader board or weekly once competition type so that to maintain some interest and competition within the users that are in the guild with some entry free ( 10 tears for example) to play the game.

This will be fun, productive and interesting.

**Comment by Vyvy-vi** [comment]
Great idea 👍 
However, how do you propose the user spends `tears`?
Is it that they need to pay some 'X' amount for playing or is it that they need to pay to get hints?

**Comment by jveer634** [comment]
They need to spend tears to play..
Hints in the game may be or may not be possible all the times..

**Comment by jveer634** [comment]
And if possible we can even maintain categories for the game.. and different entry fee for the category.

**Comment by Vyvy-vi** [comment]
🤔

**Comment by jveer634** [comment]
https://github.com/jgoralcz/trivia

Look at this repo for the questions..

**Comment by Vyvy-vi** [comment]
I'm not sure if they host the API 24x7, also the API seems to be under development, rather than production
(using this might have un-intended consequences) 

However, the API is interesting. (We could look for similar APIs and checkout one that is in production)

**Comment by jveer634** [comment]
Or we could build some api by ourself but the problem is to search for the questions and upload them frequently.. any idea to resolve that..??

**Comment by Vyvy-vi** [comment]
I don't think building our own API is a good idea, since that would add another thing that we'll need to use and since things like those are already implemented, making one might be inefficient...

(We could make an API but that would become a sub-project by itself)
Moreover, we could just request data from trivia sites and get random questions every time. (that might resolve the similar questions problem)

**Comment by Vyvy-vi** [comment]
Perhaps we could use https://quizapi.io/
and make our own quiz sets and query them using their API ?

**Comment by Vyvy-vi** [comment]
Alternatively, if we're making an API, I could just make anther db in our mongo cluster to hold the questions. (this would make the hosting part easier and we could just use Mongo's query calls to fetch the data, which would be faster)

**Comment by jveer634** [comment]
The quizapi fits fine..

**Comment by Vyvy-vi** [comment]
Okay, for now we could use the quizapi 👍 
Would you like to work on this? 

About making our own API:
(I'll see if later on, we could use our own version, I think we could just use the pre-existing mongoAPI to fetch data that we put on there, rather than creating our own API)

**Comment by jveer634** [comment]
Yes.. I like work on that.. but after a week.

**Comment by Vyvy-vi** [comment]
I have assigned this issue to you for now(so that someone else doesn't end up doing this, while you also work on it)

You could make your contributions in a week, no problem 👍  (tho, stale-bot might have an issue if no-activity for more than 3 weeks)

**Comment by AkshayaKulasekaran** [comment]
I think this could be cool! Maybe you could tie it up with the quotes?

**Comment by Vyvy-vi** [comment]
> I think this could be cool! Maybe you could tie it up with the quotes?

Tying it with quotes? 🤔 
Sounds good! Could you extend, what you have in your mind?
