### ISSUE TITLE
[CHORE] Rename cog files

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TearDrops#199]
# Chore Request

## Describe the work

Rename the cog files in `bot/cogs` folder to type- `<function>` instead of `function_cog`
Eg: Rename `economy_cog.py`to `economy.py`

## Additional information

You would also have to update the names imported in the `bot/main.py` file.

https://github.com/Vyvy-vi/TearDrops/blob/5a11525abbad37de9dda9f31fc54a4c4682b5656/bot/main.py#L30-L43

**Comment by kcoder63** [comment]
I would like to work on this
