### ISSUE TITLE
[BUG]: wiki command issues

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TearDrops#23]
The bot's wiki commands sometimes yields unicode chars(*my terminology might be wrong here) and those look weird in the command. For now, try removing those characters by string manipulation
![Screenshot 2020-10-30 at 10 34 10 AM](https://user-images.githubusercontent.com/62864373/97661839-77608780-1a9b-11eb-9448-256248fcdb26.png)

**Comment by anubhavcodes** [comment]
@Vyvy-vi 

From discord. I will take this up. :)

**Comment by gamerrio** [comment]
ok fixed will push changes in few secs

**Comment by Vyvy-vi** [comment]
um @anubhavcodes  This issue just got fixed in #33 
Sorry...
If you want to still work on good issues, maybe you can build the help command
