### ISSUE TITLE
not all commands working in help menu

### ISSUE THREAD

**Issue by gamerrio** [Vyvy-vi/TearDrops#36]
not all commands work in help command. It will be better to use default command help command and editing it to make it look fancy

**Comment by Vyvy-vi** [comment]
checkout #34

**Comment by Vyvy-vi** [comment]
@all-contributors add @gamerrio ideas

**Comment by gamerrio** [comment]
I'll take this task

**Comment by Vyvy-vi** [comment]
LGTM!

**Comment by Vyvy-vi** [comment]
@all-contributors add @gamerrio code

**Comment by Vyvy-vi** [comment]
@all-contributors add @gamerrio design
