### ISSUE TITLE
[CHORE]: Add all-contributors

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TearDrops#47]
: )

**Comment by Vyvy-vi** [comment]
@all-contributors add @AllanRegush ideas

**Comment by Vyvy-vi** [comment]
@all-contributors add @RascalTwo bug

**Comment by Vyvy-vi** [comment]
@all-contributors add @Vyvy-vi design doc maintenance review

**Comment by Vyvy-vi** [comment]
@all-contributors add @all-contributors docs

**Comment by Vyvy-vi** [comment]
@all-contributors add @sayand0122 for ideas

**Comment by Vyvy-vi** [comment]
@all-contributors add @nhcarrigan ideas docs

**Comment by Vyvy-vi** [comment]
Nick's ISSUE set was used here as I found it fitting : )

**Comment by Vyvy-vi** [comment]
@all-contributors add @MattIPv4 ideas

**Comment by Vyvy-vi** [comment]
@all-contributors add @all-contributors docs

**Comment by Vyvy-vi** [comment]
@all-contributors add @all-contributors docs

**Comment by Vyvy-vi** [comment]
@all-contributors add @all-contributors docs

**Comment by Vyvy-vi** [comment]
@all-contributors add @all-contributors docs

**Comment by nhcarrigan** [comment]
Psst - you don't have to keep a global issue open for this. You can ping all contributors to add someone on the PR/issue they opened :)

**Comment by Vyvy-vi** [comment]
(I kept this open to add contributors for ideas, but I think I'll add them with a new issue or something) :+1:

**Comment by nhcarrigan** [comment]
Or encourage them to share their ideas as an issue/feature-request - that way you keep the discussion tied to your repository
