### ISSUE TITLE
[suggestion ] : A slap command command which virtually slap another person

### ISSUE THREAD

**Issue by gamerrio** [Vyvy-vi/TearDrops#64]
A slap command which some cool and fun gif list

**Comment by sayand0122** [comment]
Is this issue solved?

**Comment by Vyvy-vi** [comment]
@gamerrio is assigned to it

**Comment by sayand0122** [comment]
ok

**Comment by Vyvy-vi** [comment]
@gamerrio Are you still working on this?
I saw that your version of the bot, gave output for the command.
So, if it's done, it would be nice if you made a PR.

**Comment by Vyvy-vi** [comment]
Take your time 👍

**Comment by Vyvy-vi** [comment]
Shifting this to Build v1.1
Might make a release soon

**Comment by Vyvy-vi** [comment]
Are you working on this issue, or should I unassign you?

**Comment by sayand0122** [comment]
currently i am not working on this issue

**Comment by Vyvy-vi** [comment]
@gamerrio you have been unassigned, since the period of response was too long
If you're still interested in contributing, you could ask and get re-assigned :+1:
