### ISSUE TITLE
[CHORE]: fix embeds

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TearDrops#67]
embed commands

**Comment by sayand0122** [comment]
Do you mean all the embeds present in the code?

**Comment by Vyvy-vi** [comment]
I mean the embeds in the entertainment commands below async def magiball():

https://github.com/Vyvy-vi/TearDrops/blob/89a2948d6cf0e47caac9349d93ae5b1da75053f9/bot/main.py#L582

**Comment by sayand0122** [comment]
I am already on it

**Comment by Vyvy-vi** [comment]
will take some time for reviewing anubhav's Pr #76 
You can make the pr for the embeds now 👍
