### ISSUE TITLE
Dockerize the app for easy development.

### ISSUE THREAD

**Issue by anubhavcodes** [Vyvy-vi/TearDrops#71]
At them moment, we have some configuration hardcoded in the app, which is not so good practise IMO.

If we can dockerize the application we can have the benefits of:

- Having an image that have all the dependencies of the app baked in and ready to be deployed in a container running inside docker. 
- Use `docker-compose` to run `docker-compose up` on dev machine which spins up the app in a container and mongodb and other dependent component without any effort. The app receives the configuration of mongodb (host, port etc) via env vars which be also be setup in `docker-compose`. 
- On production, we can deploy the app in an image using one of the 100 options available (Heroku docker deplyments, AWS ECS service, Kubernetes on any cloud etc) 

Let me know your thoughts on these.

**Comment by Vyvy-vi** [comment]
Good issue!
I was just looking into docker images and how dockerising bots makes it more efficient(something to do with uptime I think).
Would be great if you help out.
I have currently labeled this under v1.1 as in v1.0, I plan on finishing commands and then move to cogs in 1.1, where we can also pick up docker-containers. You could help with this in the meantime tho
👍 :

**Comment by Vyvy-vi** [comment]
@all-contributors add @anubhavcodes for ideas
