### ISSUE TITLE
[FEAT]: Make currency spending system(Casino)

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TearDrops#8]

**Comment by sayand0122** [comment]
Lets now do this... Any ideas on like what exactly you thought when you wrote casino?

**Comment by Vyvy-vi** [comment]
Yah, I am working on this rn.
We should pool ideas for this first, before making commands.
Let's discuss on the main concerns regarding the economy system:

- users need to spend token('tears') on stuff
- this spend can be promoted by having a store and having a casino

- casino might be just a set of command like the pre-existing diceroll command, attatched to a money prize
- we can think of something along the lines of having a slot, a coin-toss-bet, guess the card
- or we can go a step further an make a blackjack command

- Another idea I had was since the bot is based on crying, maybe we can make it partially unfavourable to a user after say every third command usage?

**Comment by Vyvy-vi** [comment]
About the store, I am trying to get some custom emoji's etc for items that we can display in a store(but I'll keep the store for build v1.1+)

**Comment by sayand0122** [comment]
So we already have a diceroll command... ok so
Now i was thinking we can have something they(people) can spend the currency(tears) on 

For ex - a collection of emojis/surprise box that they need to buy with those tears

**Comment by Vyvy-vi** [comment]
Yah badges and level-cards are a part of the plan but not rn
That'll be in build v1.1+ (we can implement this idea over there tho, after making the normal commands for now and adding badges.)
The problem with surprise boxes is that we'll need custom emojis in there.
Might have to make them... Then maybe find out how to get them onto bots(custom emoji issues/nitro?)

**Comment by sayand0122** [comment]
ok so this issue is for later but like when in v1.1+ release ... what i mean is when according to you will v1.0 end?

**Comment by Vyvy-vi** [comment]
When we have like 3-4 casino commands and when all the current issues are closed.
https://github.com/Vyvy-vi/TearDrops/projects
